# syntax = edrevo/dockerfile-plus
ARG IMAGE=containers.intersystems.com/intersystems/iris-community:latest-cd

INCLUDE+ Dockerfile-phase1

FROM --platform=linux/amd64 $IMAGE as x86

INCLUDE+ Dockerfile-phase2