ARG IMAGE=intersystems/iris-community:latest-cd
ARG DEV=0
FROM --platform=${BUILDPLATFORM} $IMAGE

ARG IPM_INSTALLER=https://pm.community.intersystems.com/packages/zpm/latest/installer

COPY ./iris.script /tmp/iris.script

RUN \
  wget -q $IPM_INSTALLER -O /tmp/zpm.xml && \
  mkdir /usr/irissys/mgr/zpm && \
  iris start $ISC_PACKAGE_INSTANCENAME quietly && \
  iris session $ISC_PACKAGE_INSTANCENAME -U %SYS < /tmp/iris.script && \
  iris stop $ISC_PACKAGE_INSTANCENAME quietly
